# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apeiria/qt_Apeiria.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 680)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(5, 0, 340, 500))
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setObjectName("listWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 540, 611, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.buttonTalk = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTalk.setGeometry(QtCore.QRect(680, 540, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonTalk.setFont(font)
        self.buttonTalk.setObjectName("buttonTalk")
        self.labelResponce = QtWidgets.QTextBrowser(self.centralwidget)
        self.labelResponce.setGeometry(QtCore.QRect(350, 310, 501, 192))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelResponce.setFont(font)
        self.labelResponce.setObjectName("labelResponce")
        self.labelShowing = QtWidgets.QLabel(self.centralwidget)
        self.labelShowing.setGeometry(QtCore.QRect(310, 0, 621, 311))
        self.labelShowing.setText("")
        self.labelShowing.setPixmap(QtGui.QPixmap(":/re/デフォルト.png"))
        self.labelShowing.setObjectName("labelShowing")
        self.labelexpression = QtWidgets.QLabel(self.centralwidget)
        self.labelexpression.setGeometry(QtCore.QRect(310, 0, 621, 311))
        self.labelexpression.setText("")
        self.labelexpression.setObjectName("labelexpression")
        self.labelemotion = QtWidgets.QLabel(self.centralwidget)
        self.labelemotion.setGeometry(QtCore.QRect(310, 0, 621, 311))
        self.labelemotion.setText("")
        self.labelemotion.setObjectName("labelemotion")
        self.radioButton_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_1.setGeometry(QtCore.QRect(30, 520, 130, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(200, 520, 130, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuclose = QtWidgets.QAction(MainWindow)
        self.menuclose.setObjectName("menuclose")
        self.menu.addAction(self.menuclose)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.buttonTalk.clicked.connect(MainWindow.buttonTalkSolt) # type: ignore
        self.menuclose.triggered.connect(MainWindow.close) # type: ignore
        self.radioButton_2.clicked['bool'].connect(MainWindow.voiceON) # type: ignore
        self.radioButton_1.clicked['bool'].connect(MainWindow.voiceOFF) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonTalk.setText(_translate("MainWindow", "話す"))
        self.radioButton_1.setText(_translate("MainWindow", "音声認識OFF"))
        self.radioButton_2.setText(_translate("MainWindow", "音声認識ON"))
        self.menu.setTitle(_translate("MainWindow", "メニュー"))
        self.menuclose.setText(_translate("MainWindow", "閉じる"))
import recource_rc
